### ISSUE TITLE
text alignment off

### ISSUE THREAD

**Issue by jasonehines** [joshymcd/mycroft-magic-mirror#3]
I'm not familiar enough with node to help with the code, but the text history could use a border to prevent it from running into the 'Ask Mycroft' text.
![mycroft-magic-mirror_text-issue](https://cloud.githubusercontent.com/assets/870809/16570462/a3da1af2-4213-11e6-8f8d-4200b5563b78.png)

**Comment by joshymcd** [comment]
ahh yes,
i will add a fix in my next commit :)

**Comment by joshymcd** [comment]
due to the change in project struct i will add this as an issue to the mycroft-electro-plugins repo
https://github.com/joshymcd/mycroft-electro-plugins

**Comment by joshymcd** [comment]
This issue was moved to joshymcd/mycroft-electro-plugins#1
